{% set name='py2neo' %} 
{% set version='4.1.3' %}
{% set sha256='6123ead0b238662d93a308f20be728454ee6c3e0569fd5497b05fc410b2488bd' %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    # patch to fix writing to the console in unicode in python2/3 friendly way
    - console.patch

build:
  script: python setup.py install --single-version-externally-managed --record=record.txt
  entry_points:
    - py2neo = py2neo.cli.tool:main
    - neokit = neokit:main
    - geoff = py2neo.ext.geoff.__main__:main
  number: 0

requirements:
  build:
    - python
    - setuptools
    - neo4j-python-driver ==1.1.0rc1
    - urllib3
  run:
    - python
    - neo4j-python-driver ==1.1.0rc1
    - urllib3

test:
  imports:
    - py2neo
    - py2neo.ext
    - py2neo.ext.calendar
    - py2neo.cli
    - py2neo.cypher
  commands:
    - echo '/exit' |py2neo 2>&1|grep Py2neo >/dev/null  # [not win]
    # neokit broken in py2neo 4.0.0b2
    # - neokit

about:
  home: http://py2neo.org/
  license: Apache-2.0
  license_file: LICENSE
  summary: 'Python client library and toolkit for Neo4j'

extra:
  recipe-maintainers:
    - pvanheus
