travis:
  secure:
    BINSTAR_TOKEN: pc3HpkMxs27nH3/w0J3+cUuYmXJgM4D02uFf2a5FSksRog/SMS9Y6LOQgn2hmRzdMJS72XT9zVzgd6xc97gS2aUX6nA3hXfdcW3jVk+xh2UfJCqugyoYSRHMntXEGqreoqwCIBN/Q1sTRSDYIEtBlm2JZVjY/DTgizURUScbclm+S/RYnQF3iEUiNHllXOx+HLbxpxA9HU/2UtG8g+0mkaVIPWnZYrzsSeBlAk0MOtYq3mH7vtj+uSqaaLmRIn7++owKoq35VNWeEsJr0dsXNZ7CN+kr1HUxy2N7IUCpk1ifVHnyoJnhMgQo08STHnbmFlOd+PMJFnNqsFJuHgRl8cz1utDwkniYGiZc7L3NEijgOtOQe0MXQaCvFehYyoh5rRiw8x64YyoDbodCuGZbhecp/6dOvUYAsoDubgG67c/nl0/2u/EacoKZllGAZm1kdmX/x3iMYE/TEj4qjA+/SjgDHZMboQT56CHqg52UeN7j6xRQzGO+Gm1eis/c/koURH5CuFuw7jLOeyBFfk/BmaWRM1Y1DNwClJdX4tl+URIIWrgzvDsvnR2cCzrsekWyy0kok1Jfb2LYf5R59/nO75QylEImUMUzj1CNHpVdWCqFY44vibDjWz4EdJyi6thyGHyJm0IoTaMEkszJQeJLx6OG3yEvXle9pI73NbN9gwA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
